### ISSUE TITLE
Traffic being lost with amass 2.9.4

### ISSUE THREAD

**Issue by laoshaw** [OWASP/Amass#135] opened 2019-03-27 03:17 UTC
Run 2.9.4 with `amass -d target.com -o target.com.txt` on ubuntu 18.04 suddenly I got a fast scrolling screen of below messages:

```
goroutine 588951 [chan send]:
github.com/OWASP/Amass/amass/utils.(*StringFilter).Duplicate(...)
	/build/amass/parts/amass/go/src/github.com/OWASP/Amass/amass/utils/misc.go:49
github.com/OWASP/Amass/amass.(*NameService).newNameEvent(0xc003ef2180, 0xc00d9c7b20)
	/build/amass/parts/amass/go/src/github.com/OWASP/Amass/amass/namesrv.go:73 +0x2bc
github.com/OWASP/Amass/amass.(*NameService).newNameEvent-fm(0xc00d9c7b20)
	/build/amass/parts/amass/go/src/github.com/OWASP/Amass/amass/namesrv.go:52 +0x34
reflect.Value.call(0xaeeb00, 0xc00a03e1f0, 0x13, 0xbf3c66, 0x4, 0xc0155310a0, 0x1, 0x1, 0xc030871750, 0x10, ...)
	/build/amass/parts/go/build/src/reflect/value.go:447 +0x449
reflect.Value.Call(0xaeeb00, 0xc00a03e1f0, 0x13, 0xc0155310a0, 0x1, 0x1, 0x0, 0xbf45d4, 0xc03d46a5a0)
	/build/amass/parts/go/build/src/reflect/value.go:308 +0xa4
github.com/OWASP/Amass/amass/core.(*EventBus).executeCallbacks(0xc0001d8150, 0xc00c60c0c0, 0x1, 0x1, 0xc0155310a0, 0x1, 0x1)
	/build/amass/parts/amass/go/src/github.com/OWASP/Amass/amass/core/request.go:170 +0xcc
created by github.com/OWASP/Amass/amass/core.(*EventBus).processRequests
	/build/amass/parts/amass/go/src/github.com/OWASP/Amass/amass/core/request.go:160 +0x208

```

**Comment by fork-while-fork** [comment] 2019-03-27 13:45
I'm unable to reproduce the issue. Can you run it again and try to capture all of the error output?

`amass -d target.com -o target.com.txt 2> stacktraceoutput`

I'll need the first stack trace to diagnose the issue.

**Comment by panchocosil** [comment] 2019-03-27 19:48
Hello fork-while-fork, laoshaw. I get this same problem. Looks like its a memory bug..  What system are you using  laoshaw?
 
Other similar reports in [#122](https://github.com/OWASP/Amass/issues/122) https://github.com/OWASP/Amass/issues/12 - fixed?

I get  this error starting with `fatal error: runtime: out of memory` I'm using two CPU cores. I think amass need to reduce memory consumption.

**Comment by laoshaw** [comment] 2019-03-27 21:26
was going to reproduce tonight as I have no access to my vps here, anyway it's DigitalOcean VPS(1GB RAM), it used to be fine with amass.

**Comment by laoshaw** [comment] 2019-03-28 00:29
Update: it's a 2GB DO droplet, using "top" I noticed 1.9GB out of 2GB is used by amass however swap was never used. As you can see in the logfile it has "fatal error: runtime: out of memory" at the start which is strange. log attached:

[stacktraceoutput.gz](https://github.com/OWASP/Amass/files/3015749/stacktraceoutput.gz)

**Comment by caffix** [comment] 2019-03-28 12:46
I our experience, you should run Amass on a system that has at least 4GB of memory, 8GB would probably be better. The enumeration process maintains a lot of data. Also, if your target causes Amass to not detect a DNS wildcard, it can cause a lot of memory to be consumed. This can be addressed by blacklisting the subdomain that contains the undetected wildcard.

**Comment by laoshaw** [comment] 2019-03-28 14:04
I used aquatone and other subdomain tools in the past none had such memory requirements, I did not see this with older versions with amass either but then I did not use amass a lot yet.

I used this kind of tool once a while on my vps, normally 1GB or 2GB instances, require 4GB/8GB just to use amass is a little more than I expect, can it use filesystem to cope with storage need?

**Comment by caffix** [comment] 2019-03-28 15:07
Amass performs in-depth DNS enumeration and network mapping, and is not the same as aquatone or other subdomain enumeration tools. The data is already being stored within secondary storage using a graph database, yet some of it is still kept in memory for performance. Some of this has been improved for the next release, but I do not think you'll want to run Amass on systems with only one or two gigs of memory

**Comment by laoshaw** [comment] 2019-03-28 20:47
In that case, is it possible to make network-mapping an option, that way if I just want to run a quick analysis for subdomains I can use less resource with shorter running time, I only enable network-mapping when I need it?

**Comment by caffix** [comment] 2019-03-28 22:27
The use of the graph to manage the data collected is only disabled by using the '-passive' flag. Otherwise, the graph is required by the architecture

**Comment by snoopsnoop** [comment] 2019-04-01 12:54
I am having this same issue as well. Amass utilizes all RAM given to it in my Debian VM, currently have given it 12GB.

**Comment by nirvana-msu** [comment] 2019-04-18 22:47
I can confirm the memory consumption pattern changed in release 2.9.4. I used to have no issues running certain scans on 4GB VPS  - but after I updated to 2.9.4 it started quickly running out of memory. I had the same symptoms in the past when alterations were enabled by default. I previously addressed that by disabling alterations (`alterations=false` in the old config). 2.9.4 introduced some changes (including config changes) to alterations, so my best guess was that somehow the alterations got enabled (even though I have not enabled them in the config).

I have now updated to 2.9.9 and the memory consumption seems back in line with pre-2.9.4 levels.

**Comment by caffix** [comment] 2019-04-19 00:42
@nirvana-msu I would give the VM at least 8GB of memory. The graph database employed by Amass definitely uses quite a bit of memory. Still, we will continue to reduce memory consumption wherever possible

**Closed** 2019-05-17 22:04 UTC

**Comment by simonuvarov** [comment] 2019-05-24 10:13
I receive the same error on VPS with 4GB RAM when the "alternation" feature is enabled.

```
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0xcd15ba, 0x16)
        /usr/local/go/src/runtime/panic.go:617 +0x72
runtime.sysMap(0xc0ec000000, 0x4000000, 0x13f5f78)
        /usr/local/go/src/runtime/mem_linux.go:170 +0xc7
runtime.(*mheap).sysAlloc(0x13dd820, 0x58c000, 0x13dd830, 0x2c6)
        /usr/local/go/src/runtime/malloc.go:633 +0x1cd
runtime.(*mheap).grow(0x13dd820, 0x2c6, 0x0)
        /usr/local/go/src/runtime/mheap.go:1232 +0x42
runtime.(*mheap).allocSpanLocked(0x13dd820, 0x2c6, 0x13f5f88, 0x13dd830)
        /usr/local/go/src/runtime/mheap.go:1150 +0x3a7
runtime.(*mheap).alloc_m(0x13dd820, 0x2c6, 0x7f7437b20100, 0x7f7437b2b310)
        /usr/local/go/src/runtime/mheap.go:977 +0xc2
runtime.(*mheap).alloc.func1()
        /usr/local/go/src/runtime/mheap.go:1048 +0x4c
runtime.(*mheap).alloc(0x13dd820, 0x2c6, 0x10100, 0x200)
        /usr/local/go/src/runtime/mheap.go:1047 +0x8a
runtime.largeAlloc(0x58c000, 0xc000060001, 0x45493b)
        /usr/local/go/src/runtime/malloc.go:1055 +0x99
runtime.mallocgc.func1()
        /usr/local/go/src/runtime/malloc.go:950 +0x46
runtime.systemstack(0x0)
        /usr/local/go/src/runtime/asm_amd64.s:351 +0x66
runtime.mstart()
        /usr/local/go/src/runtime/proc.go:1153

goroutine 30663 [running]:
runtime.systemstack_switch()
        /usr/local/go/src/runtime/asm_amd64.s:311 fp=0xc011ee8b60 sp=0xc011ee8b58 pc=0x456710
runtime.mallocgc(0x58c000, 0xba7160, 0x3711ee8c01, 0x6)
        /usr/local/go/src/runtime/malloc.go:949 +0x872 fp=0xc011ee8c00 sp=0xc011ee8b60 pc=0x40bd32
runtime.growslice(0xba7160, 0xc0cb950000, 0x47000, 0x47000, 0x47001, 0x7, 0x38c00, 0x47000)
        /usr/local/go/src/runtime/slice.go:181 +0x1e6 fp=0xc011ee8c68 sp=0xc011ee8c00 pc=0x441b56
github.com/OWASP/Amass/amass.(*AlterationService).additions(0xc003f200a0, 0xc03d040000, 0x1f34b, 0x1f400, 0xc031a0c000, 0x1f1f9, 0x21400)
        /go/src/github.com/OWASP/Amass/amass/alteration.go:291 +0x237 fp=0xc011ee8e58 sp=0xc011ee8c68 pc=0xb0ac47
github.com/OWASP/Amass/amass.(*AlterationService).fuzzyLabelSearches(0xc003f200a0, 0xc00e882540)
        /go/src/github.com/OWASP/Amass/amass/alteration.go:263 +0x1a5 fp=0xc011ee8f30 sp=0xc011ee8e58 pc=0xb0a545
github.com/OWASP/Amass/amass.(*AlterationService).executeAlterations(0xc003f200a0, 0xc00e882540)
        /go/src/github.com/OWASP/Amass/amass/alteration.go:121 +0x1cc fp=0xc011ee8fd0 sp=0xc011ee8f30 pc=0xb08e8c
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc011ee8fd8 sp=0xc011ee8fd0 pc=0x458661
created by github.com/OWASP/Amass/amass.(*AlterationService).OnLowNumberOfNames
        /go/src/github.com/OWASP/Amass/amass/alteration.go:86 +0x51

goroutine 1 [runnable]:
github.com/OWASP/Amass/amass.(*Enumeration).Start(0xc000998000, 0x0, 0x0)
        /go/src/github.com/OWASP/Amass/amass/amass.go:185 +0x547
main.main()
        /go/src/github.com/OWASP/Amass/cmd/amass/main.go:392 +0x1241

goroutine 19 [syscall]:
os/signal.signal_recv(0x0)
        /usr/local/go/src/runtime/sigqueue.go:139 +0x9c
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.init.0
        /usr/local/go/src/os/signal/signal_unix.go:29 +0x41
```
