### ISSUE TITLE
Bug in the enum brute.

### ISSUE THREAD

**Issue by Rbcafe** [OWASP/Amass#262] opened 2019-09-15 06:14 UTC
Greetings,
--

I observed a bug in the enum brute.

`Amass v3.1.4`

Command : 
--

`amass enum -brute -d test.com`

Response : 
--

` Improper mask used: <a class="btn btn-sm btn-with-count tooltipped tooltipped-s" aria-label="you must be signed in to fork a repository" rel="nofollow" data-hydro-click="{&quot;event_type&quot;:&quot;authentication.click&quot;,&quot;payload&quot;:{&quot;location_in_page&quot;:&quot;repo details fork button&quot;,&quot;repository_id&quot;:140457254,&quot;auth_type&quot;:&quot;log_in&quot;,&quot;client_id&quot;:null,&quot;originating_request_id&quot;:&quot;c5fc:1e6bb:2fe5eb8:4a0dfdd:5d7dd587&quot;,&quot;originating_url&quot;:&quot;https://github.com/owasp/amass/blob/master/examples/wordlists/namelist.txt&quot;,&quot;referrer&quot;:null,&quot;user_id&quot;:null}}" data-hydro-click-hmac="3afcc64d4b0c6dbc0edd0e1023e4f170297aa6f0d76d30e322861676e562649b" href="/login?return_to=%2fowasp%2famass">`

Path :
--

https://github.com/OWASP/Amass/blob/05a190ddeeaeb0730ee2a3d18e63c3bf9f62d049/wordlist/wordlist.go

Best regards.

@Rbcafe

**Comment by drankje** [comment] 2019-09-15 08:55
This was caused by 24c7a00. One has to be logged in to obtain files from this new url. 
Quick fix would be to make use of https://github.com/settings/tokens.
But that'd possibly be insecure.
Another possible fix would be to change the lines to those, which sometimes "work":
https://raw.githubusercontent.com/OWASP/Amass/master/examples/wordlists/namelist.txt
https://raw.githubusercontent.com/OWASP/Amass/master/examples/wordlists/alterations.txt

A better fix would be to relocate the wordlists within the codebase.

**Comment by caffix** [comment] 2019-09-15 19:52
This has been fixed in v3.1.5

**Closed by caffix** 2019-09-15 19:52 UTC

**Comment by Rbcafe** [comment] 2019-09-15 21:04
Great !
