### ISSUE TITLE
Out of memory 

### ISSUE THREAD

**Issue by mgrigorov** [OWASP/Amass#12] opened 2018-07-27 11:05 UTC
I'm using virtual machine with 2GB RAM from one of the cloud providers. I faced out of memory error with amass. Could you please help me with this issue?

```
$ uname -a
Linux bbsm 4.17.9-1-ARCH #1 SMP PREEMPT Sun Jul 22 20:23:36 UTC 2018 x86_64 GNU/Linux
```

```
$ go version
go version go1.10.3 linux/amd64
```

```
$ amass -version
version v2.3.3
```

```
$ amass -active -d criteo.com -o output.txt
```

[amass_stacktrace.txt](https://github.com/OWASP/Amass/files/2235532/amass_stacktrace.txt)

**Comment by mgrigorov** [comment] 2018-07-27 13:15
Updated amass to the latest v2.4.1 but still out of memory error.
[amass_stacktrace_2.4.1.txt](https://github.com/OWASP/Amass/files/2235840/amass_stacktrace_2.4.1.txt)

**Comment by mgrigorov** [comment] 2018-07-27 15:37
Tried GCP VM instance with 8GB memory and still out of memory
[amass_stacktrace_gpc.txt](https://github.com/OWASP/Amass/files/2236370/amass_stacktrace_gpc.txt)

**Comment by mgrigorov** [comment] 2018-07-28 04:45
Thanks @caffix!
JFYI, VM instance with 26 GB RAM also faced out of memory error.
[amass_stacktrace_GCP_26GB_RAM.txt](https://github.com/OWASP/Amass/files/2237691/amass_stacktrace_GCP_26GB_RAM.txt)

**Comment by caffix** [comment] 2018-07-28 04:56
Very strange! My development system has never run out of memory during an enumeration, even when the domain contained thousands of subdomain names.

**Comment by mgrigorov** [comment] 2018-07-28 16:38
Yeah, it's strange...
![capture](https://user-images.githubusercontent.com/2330914/43358651-bc821e9c-929d-11e8-8949-67b2a67b9432.PNG)

**Comment by mgrigorov** [comment] 2018-07-28 21:35
Just for the record - 
![capture](https://user-images.githubusercontent.com/2330914/43360799-f459f096-92c6-11e8-8db6-23b9ddcd3d51.PNG)

It looks like a memory leak. VM is almost ran out of free RAM. Amass meanwhile generated ~5MB file with ~174k subdomains.

**Comment by CharlieEriksen** [comment] 2018-07-30 16:45
Also having out of memory issues on v2.4.1

**Comment by caffix** [comment] 2018-08-01 19:29
I'd appreciate it if you could try again with 2.4.2 and share the results. Thank you!

**Comment by mgrigorov** [comment] 2018-08-01 19:43
Sure, no worries

**Comment by mgrigorov** [comment] 2018-08-02 08:17
@caffix,

I tried to run amass v2.4.2 on GCP VM instance with 3.75 GB RAM. And it ended up with out of memory error =\
It ran out of memory pretty quickly
```real    6m0.474s
user    3m29.752s
sys     0m54.460s```

**Comment by CharlieEriksen** [comment] 2018-08-02 08:41
Seems to happen mostly for me when I run into domains that answer all queries with a result. If I filter out those, I don't ever run out of memory.

**Comment by caffix** [comment] 2018-08-04 03:33
Earlier, I was able to reproduce the behavior you have been experiencing. Try version 2.5.0, and let me know if your situation improves. Thanks!

**Comment by mgrigorov** [comment] 2018-08-04 18:17
Still no luck =\
VM instance with 15 GB RAM faced OOM error.

![capture](https://user-images.githubusercontent.com/2330914/43679295-97bee7d2-982b-11e8-9d4b-6e40cb57f945.PNG)

amass v2.5.0

`amass -active -d criteo.com -o results.txt`

**Comment by h3ku** [comment] 2018-08-08 06:25
I'm facing some issues with the latest version.
![image](https://user-images.githubusercontent.com/5603877/43819804-8cd7e844-9ae4-11e8-91ea-cee5f3140ec2.png)

I really don't know why.

**Comment by CharlieEriksen** [comment] 2018-08-08 16:00
I'm seeing improved behaviour in this regard on 2.5.1. amass no longer takes up 100% CPU the first 1-2 minutes now at least.

**Comment by h3ku** [comment] 2018-08-10 18:18
I'm facing the same memory overhead problems on 2.5.2.

**Comment by caffix** [comment] 2018-08-11 01:47
The problem seems to be less severe, yet I have been able to recreate the issue, and will continue to dig into it.

**Comment by CharlieEriksen** [comment] 2018-08-20 12:15
I'm not running into it anymore. But I've also started running an amass process for each domain. So I'm not passing multiple domains to each process, which probably helps.

**Comment by caffix** [comment] 2018-08-29 01:11
I am seeing even better results for version 2.6.1! Can some of you test this and provide feedback? Thank you in advance!

**Comment by caffix** [comment] 2018-08-31 23:07
@mgrigorov Your target has a wildcard capable of tricking the Amass detection algorithm. Thank you for bringing me this interesting test case! In the meantime, try using the following command instead:

amass -v -ip -active -bl widget.criteo.com -d criteo.com -o criteo.txt

I'll see what can be done to improve the wildcard detection.

**Comment by mgrigorov** [comment] 2018-09-01 20:44
> amass -v -ip -active -bl widget.criteo.com -d criteo.com -o criteo.txt
wow, thanks for helping! Worked like a charm!

**Comment by caffix** [comment] 2018-09-04 19:37
@mgrigorov Happy to be able to help, and we'll continue to address the memory issue.

**Comment by caffix** [comment] 2018-09-12 01:45
Since the Amass memory consumption has been behaving well, I'm going to close this issue unless users continue to experience problems.

**Closed by caffix** 2018-09-12 01:45 UTC

**Comment by Jineeshak** [comment] 2019-06-02 08:59
@caffix   9 GB memory usuage , while running amass intel command

**Comment by phackt** [comment] 2019-06-26 17:09
Hello, i m experiencing the same issue (below dmesg results) with command ```amass enum -active -p 443 -src -norecursive -brute -w wordlist.txt -json output.json -d netflix.com```:  

```
[1433251.205365] Out of memory: Kill process 5442 (amass) score 655 or sacrifice child
[1433251.205439] Killed process 5442 (amass) total-vm:12778192kB, anon-rss:11306512kB, file-rss:0kB, shmem-rss:0kB
```  
  
or
  
```
[4856371.424197] Out of memory: Kill process 31136 (amass) score 764 or sacrifice child
[4856371.425925] Killed process 31136 (amass) total-vm:6376016kB, anon-rss:6232076kB, file-rss:0kB, shmem-rss:0kB
```  
  
Any help should be welcomed, thanks.

**Comment by fersingb** [comment] 2019-07-25 19:28
Hello,

Same issue here. The command `amass enum -d <domain>` will trigger a OOM after some time if the domain has a lot of subdomains (VPS with 2GB of RAM)

**Comment by caffix** [comment] 2019-07-25 19:45
@fersingb A VPS of that size is likely to cause an out-of-memory error due to the graph database requirements

**Comment by fersingb** [comment] 2019-07-25 20:05
@caffix I understand, thanks for the answer. What's the minimum setup required to run amass?

**Comment by caffix** [comment] 2019-07-25 20:29
People that use a 4GB VPS do not seem to have trouble, but it really just depends on how large your scope is and the size of your wordlists used for brute forcing techniques

**Comment by Rz-Rz** [comment] 2021-04-05 19:32
Just got OOM issue on a 4gb VPS! My wordlist might be too long, I'm trying on a 16gb ram VPS
![2021-04-05 21_31_04-root@findomain-amass-s-2vcpu-4gb-nyc1-01_ ~_amass_linux_amd64](https://user-images.githubusercontent.com/52322219/113617116-48f06500-9656-11eb-8f31-39ce1dcfbec2.png)

**Comment by Swiffers** [comment] 2021-06-10 16:46
"Dirty" but working: enable swap memory if you are low on ram.

**Comment by deatkcjn** [comment] 2022-03-22 00:36
Consumes a lot of memory, I'm using a VPS with 8G ram and I can not use the -df option with 10 domains or more.
