### ISSUE TITLE
lose interest

### ISSUE THREAD

**Issue by samuel82333** [OWASP/Amass#53] opened 2018-11-18 15:32 UTC
Hi , when I using -brute or -d Flag , I will lose my wifi interest didn't matter i use my desktop , laptop or any pc . sorry for my english , I hope you can understand me . So do u know how to fix this problem ?

**Comment by caffix** [comment] 2018-11-18 16:17
I'm going to assume that the issue is you're Losing your Internet Connection. The amass tool could be running faster than your connection can handle. Try bringing the timing down using one of the following flags: '-T 0' or '-T 1'

Please let me know if this works out for you. Thank you!

**Comment by samuel82333** [comment] 2018-11-18 16:43
Hi , when I use ./amass -brute -T 0 -d or ./amass -T 0 -d is work , my interest will got super slow and i will got average requests , but i'm agree you said (The amass tool could be running faster than your connection can handle) , so I'm sure it's the problem

**Comment by caffix** [comment] 2018-11-19 00:58
Please let me know if I can help you further, otherwise, feel free to close the issue. Thanks!

**Closed** 2018-11-20 14:50 UTC
